# Generated by gem2arch (https://github.com/anatol/gem2arch)
# Maintainer: A Farzat <a@farzat.xyz>

_gemname=svg_sprite
pkgname=$_gemname
pkgver=1.0.3
pkgrel=1
pkgdesc='Create SVG sprites using SVG links.'
arch=(any)
url='https://github.com/fnando/svg_sprite'
license=(MIT)
depends=(ruby ruby-nokogiri ruby-svg_optimizer ruby-thor)
options=(!emptydirs)
provides=(ruby-$_gemname)
source=(https://rubygems.org/downloads/$_gemname-$pkgver.gem)
noextract=($_gemname-$pkgver.gem)
sha1sums=('7332f056e2591b23cdb6f97a5a6400e8c1309751')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
  install -D -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/LICENSE.md" "$pkgdir/usr/share/licenses/$pkgname/LICENSE.md"
}
