pkgname=illogical-impulse-python
pkgver=1.0
pkgrel=1
pkgdesc='Illogical Impulse Python Dependencies'
arch=(any)
license=(None)
depends=(
  python-build
  python-pillow
  python-setuptools-scm
  python-wheel
  clang
  uv
  gtk4
  libadwaita
  libsoup3
  libportal-gtk4
  gobject-introspection
  sassc
  python-opencv
)
